### ISSUE TITLE
409 Error on gradle dependency

### ISSUE THREAD

**Issue by AppGrade-D** [RocketChat/Rocket.Chat.Java.SDK#1]
Hello,
I am trying to add this SDK in version 0.2.0 into Android project in gradle dependencies but I get 409 Conflict error.

There is how I am adding sdk:
compile ('io.rocketchat:rocketchatjavasdk:0.2.0'){
        exclude group :'org.json', module: 'json'
}

Here is an error:
{
  "errors" : [ {
    "status" : 409,
    "message" : "The repository 'oss-snapshot-local' rejected the resolution of an artifact 'oss-snapshot-local:io/rocketchat/rocketchatjavasdk/0.2.0/rocketchatjavasdk-0.2.0.pom' due to conflict in the snapshot release handling policy."
  } ]
}

Version 0.1.1 works fine, I have tested also on fresh project with clear gradle cache.

**Comment by sacOO7** [comment]
Hey it should work now :)

**Comment by AppGrade-D** [comment]
Great :)
Could you provide soem examples/docs how use new version 0.2.0?

**Comment by sacOO7** [comment]
Yeah, I'm gonna add it after some commits, it currently supports just LiveChat API of Rocket.Chat, (mostly used for support on company websites). So, meanwhile I think you should read about it :)

**Comment by AppGrade-D** [comment]
Will there be methods like:
- liveChat.login("mail", "password", listener) //to login with mail and password instead of token
- liveChat.joinRoom(???) : ChatRoom //to join existing room
- meassages witch attachments
?

I have search for that method in Android Native application (link: https://github.com/RocketChat/Rocket.Chat.Android) 
but this app does not use your SDK.

**Comment by sacOO7** [comment]
Yeah, there are methods for login and and room join. I think first you should use livechat on browser. There are some configuration settings required to be made on server side.

**Comment by sacOO7** [comment]
Hey @AndDev123321 I have added the documentation, check it out....
