### ISSUE TITLE
List Online users?

### ISSUE THREAD

**Issue by Naguchennai** [RocketChat/Rocket.Chat.Java.SDK#16]
It is possible get list of online users? online users from specific room id or name?

**Comment by sacOO7** [comment]
I'm still working on the API to get members of room. There is another API to check whether user is online or not. Will push those methods in next update. 
P.S. Let me know if there is problem with current available APIs.

**Comment by Naguchennai** [comment]
Oh thanks .. All other working fine please update as soon as user list in sdk. also need connect webrtc android to web user

**Comment by sacOO7** [comment]
Hi @naguchennai keep watching the repo., I will be adding the remaining APIs soon ....

**Comment by Naguchennai** [comment]
Yes 007 not only watching i am waiting ..

**Comment by sacOO7** [comment]
If you can try out beta version :)
use this

`compile 'io.rocketchat:rocketchatjavasdk:0.6.3'`

There is a method on ChatRoom object for getting online members named **getMembers**

**Comment by Naguchennai** [comment]
this 0.6.3 gave error with Error:(42, 35) error: cannot find symbol class SubscriptionListener, onGetSubscriptions changed?

**Comment by Naguchennai** [comment]
import io.rocketchat.core.callback.SubscriptionListener;
onGetSubscriptions also not work

**Comment by sacOO7** [comment]
Hey I think listener has been changed. Use GetSubscriptionListener instead

**Comment by Naguchennai** [comment]
No its not work pls help me this one not work

 @Override
    public void onGetSubscriptions(ArrayList<SubscriptionObject> subscriptions, ErrorObject error) {

        //Creating Logical ChatRooms using factory class
        ChatRoomFactory factory=api.getFactory();

**Comment by sacOO7** [comment]
Don't panic man, I'm always available to help you :)

**Comment by sacOO7** [comment]
```
  api.getSubscriptions(new GetSubscriptionListener() {
            @Override
            public void onGetSubscriptions(List<SubscriptionObject> subscriptions, ErrorObject error) {
                
            }
        });
```
or 
make sure you implement 
GetSubscriptionListener interface.

**Comment by sacOO7** [comment]
or 

```
 @Override
    public void onLogin(TokenObject token, ErrorObject error) {
        api.getSubscriptions(this);
    }

    @Override
    public void onGetSubscriptions(List<SubscriptionObject> subscriptions, ErrorObject error) {
        for (SubscriptionObject subscription : subscriptions) {
            System.out.println("name is "+ subscription.getRoomName());
        }
    }

```

**Comment by Naguchennai** [comment]
Yes thank u Now working fine.. Pls if possible Tell me how can i connect webrtc? any api

**Comment by Naguchennai** [comment]
room.getMembers(new RoomListener.GetMembersListener() {
Its work. but its not real time its not update for new user .

**Comment by sacOO7** [comment]
I will be adding code tonight ( after 2-3 hours) to steam all online users. There is a totally different API for it. So, please wait till then :)

**Comment by sacOO7** [comment]
Hey use this code for now 

 ```

@Override
    public void onLogin(TokenObject token, ErrorObject error) {
        api.getSubscriptions(this);
        api.subscribeActiveUsers(null);
        api.getDbManager().addObserver(new Observer() {
            @Override
            public void update(Observable o, Object arg) {
                if (arg != null) {
                    UserDocument document = (UserDocument) arg;
                    System.out.println("UserName is " + document.getUserName());
                  
                    System.out.println("New status is " + document.getStatus());
                }
            }
        });

    }
```

You can get status change of each and every online user, match username with required users and you can update their status on the required view.
Note that each callback is being executed on background thread, you need to use special method like runOnUiThread () in android or Platform.runlater in javaFX to update the view.

**Comment by Naguchennai** [comment]
working now
