### ISSUE TITLE
GetInitialData fails with JSONException: JSONObject["room"] not a string

### ISSUE THREAD

**Issue by grchis** [RocketChat/Rocket.Chat.Java.SDK#18]
When calling getInitialData, and room is null, calling object.getString["room"] will throw an exception.
I attached a screenshot with the debugger, in order to be faster to identify the issue.
Best regards,
Grig
<img width="1123" alt="screen shot 2017-08-13 at 5 22 38 pm" src="https://user-images.githubusercontent.com/12933308/29250528-78a058ba-804c-11e7-8997-e24c7eeed75c.png">

**Comment by sacOO7** [comment]
Thank you @grchis , I will surely take a look at it and will fix it as soon as possible, bug will get fixed in next update. Let me know if there are any other errors in the code.

**Comment by sacOO7** [comment]
Hey, is this really creating problem in the code. Actually my test executed without any problem. I think it's taking room as null automatically without throwing exception. Might be due to variation in Json Libraries.
Because the data returned has value null, so it should return null. Which SDK version you are using right now? Can you log the LiveChatConfiguration Object return by server in here. The SS is quite not helping me.

**Comment by sacOO7** [comment]
I think error is due to different data type of a room returned by a server. Can you please log here the data.

**Comment by grchis** [comment]
This is the value that gets passed in the LiveChatConfigObject:

`{"color":"#C1272D","offlineMessage":"We are not online right now. Please leave us a message:","language":"","title":"Everything HelpDesk","triggers":[],"displayOfflineForm":false,"enabled":true,"room":null,"offlineColor":"#C1272D","offlineTitle":"Leave a message","transcriptMessage":"Would you like a copy of this chat emailed?","offlineSuccessMessage":"","videoCall":false,"offlineUnavailableMessage":"","transcript":false,"online":true,"departments":[{"showOnRegistration":true,"name":"Click here to chat with a technician","description":"You can chat in real time with a technician","numAgents":2,"_id":"BgGqRRSgvMXrbXNFC","_updatedAt":{"$date":1502632040867},"enabled":true},{"showOnRegistration":true,"name":"Technicians","description":"This is the technicians department","numAgents":2,"_id":"KijZPJaknF9NpR9BB","_updatedAt":{"$date":1502631876519},"enabled":true},{"showOnRegistration":true,"name":"Test Department","description":"","numAgents":2,"_id":"jHqtgH9uggfhz9udz","_updatedAt":{"$date":1502632552669},"enabled":true}],"allowSwitchingDepartments":true,"registrationForm":false}`

**Comment by grchis** [comment]
The issue is that the "room" attribute is null, and when this line ` room=object.getString("room");` i executed the exception is throwned

**Comment by sacOO7** [comment]
Ohk will fix it :+1: , I will upload new version tomorrow (Beta one), let me know if I forget to do it :p

**Comment by sacOO7** [comment]
Hey there,
I have fixed the bug, fix currently available in beta version
Add this to build.gradle

`compile 'io.rocketchat:rocketchatjavasdk:0.6.3'`

Let me know if there is anything else I can do for you :+1:

**Comment by grchis** [comment]
It works now. Thanks!
