### ISSUE TITLE
When restoring the state of the room, the room is interpreted as being a new room

### ISSUE THREAD

**Issue by grchis** [RocketChat/Rocket.Chat.Java.SDK#20]
When saving the state of the room, and restoring it for sending another message to that room, it is interpreted as being a new room(A new entry with the same name is created in the rocketChat app)
This didn't reproduced in the 0.6.0 version.

Anyway, there is a very different/buggy behavior after 0.6.0 version...

**Comment by sacOO7** [comment]
What type of problem is it creating for you? Is it able to load history and other things? Room is just a logical entity provided to simplify abstraction. Once state is regained, it can be used as a original room.

**Comment by sacOO7** [comment]
Use old stable version instead, I think it will work for you :)

`compile 'io.rocketchat:rocketchatjavasdk:0.5.1'`

**Comment by sacOO7** [comment]
Any updates?

**Comment by grchis** [comment]
I used version 0.6.4 and after a few changes in my code worked. 
This issue can be closed since it is not reproducing anymore. Cheers 👍

**Comment by sacOO7** [comment]
Thanks, keep updating for more issues :+1:
