### ISSUE TITLE
When sending a message to a department, the message is not received by all agents

### ISSUE THREAD

**Issue by grchis** [RocketChat/Rocket.Chat.Java.SDK#21]
When a new user sends a message, and it is registered like this `liveChat.registerGuest(username, email, departmentId, this);` the message is not broadcasted to all agents from that department, only to the last one added.

**Comment by grchis** [comment]
I use this version: ` compile 'io.rocketchat:rocketchatjavasdk:0.6.4'`

**Comment by sacOO7** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/7398
Is this the issue you are trying to tell?

**Comment by sacOO7** [comment]
Can you give me more detailed explaination?

**Comment by sacOO7** [comment]
Hey, I will be closing the issue if it is resolved :+1: .Please let me know about it :)

**Comment by grchis** [comment]
Hi! You can close this issue. After changing a few settings in the rocketChat app, it works now.

**Comment by sacOO7** [comment]
Thank you !!! feel free to add more suggestions :). I will be closing this issue now.
