### ISSUE TITLE
Separate into modules and artifacts

### ISSUE THREAD

**Issue by luciofm** [RocketChat/Rocket.Chat.Java.SDK#22]
Separate the SDK into the modules and artifacts
livechat module - rocketchat-sdk-livechat artifact for LiveChat functionality 
core module - rocketchat-sdk-core artifact for core SDK functionality, DDP protocol comunication.
common module - rocketchat-sdk-common artifact for common code used by both livechat and core modules.

**Comment by sacOO7** [comment]
Thank you lucio, I will be adding update today (PR) in addition with some of the cool features, required for app development, for sure :+1:

**Comment by sacOO7** [comment]
Separated modules in different parts, uploaded artifacts on bintray with proper dependency handling :+1:
