### ISSUE TITLE
Get webrtc invite

### ISSUE THREAD

**Issue by Naguchennai** [RocketChat/Rocket.Chat.Java.SDK#23]
How can user get private webrtc invite? need some function about webrtc

**Comment by sacOO7** [comment]
Hi @naguchennai , we're still working on it but don't have invitations yet. Current focus is only based on websocket protocol. Please feel free to add more suggestions.

**Comment by sacOO7** [comment]
I'm currently closing this issue for now, will let you know about new updates about webrtc :+1:
