### ISSUE TITLE
[NEW] Pinned messages list

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Java.SDK#36]
# Description

Add support to fetch the pinned messages list (paginated) in the SDK as a REST API.

## Progress

- [x] API request;
- [x] Paginated support;
- [ ] Unit tests;

**Comment by sacOO7** [comment]
does this have any rest API implementation available?

**Comment by rafaelks** [comment]
@sacOO7 Yes, we're using on the Android app already.
