### ISSUE TITLE
Can I use both core SDK and livechat in the same project?

### ISSUE THREAD

**Issue by vanwidj** [RocketChat/Rocket.Chat.Java.SDK#69]
I want to insert livechat on my the core sample app.
Can I do that?

**Comment by rafaelks** [comment]
@vanwidj Yes, you can.

**Comment by vanwidj** [comment]
can I add upload file method at livechatapi?
  @rafaelks

**Comment by vanwidj** [comment]
@rafaelks

**Comment by rafaelks** [comment]
Yes.

**Comment by vanwidj** [comment]
when I imported livechat as module the API is locked..
I can't write there. it's on the rocketchatjavasdk.0.5.1.jar if Im not mistaken. @rafaelks
