### ISSUE TITLE
Any News about Core SDK?

### ISSUE THREAD

**Issue by Naguchennai** [RocketChat/Rocket.Chat.Java.SDK#8]
Any plan about Core SDK? can we wait? how many days we need to wait? or jump any other?

**Comment by sacOO7** [comment]
Hey, I think you can wait till end of next week. It might take 7-8 days from now. Preliminary part will get completed within 4-5 days. So, be patient. I am currently working on the same thing right now. So, SDK will be available for use within given timeline. Thank you for your time :)

**Comment by rafaelks** [comment]
I'm closing the issue, since the Core SDK is already in development.
